name: Main-Push

# Run this workflow every time a new commit pushed to main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Deployment Environment'
        required: true
        default: 'dev'
      logLevel:
        description: 'The Logging Level'
        required: false
        default: 'low'

jobs:
  #allow editing of manual running parameters
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Deploy Environment: ${{ github.event.inputs.deployEnvironment }}"
        echo "Log Level: ${{ github.event.inputs.logLevel }}"

  buildx:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1.5.1
        with:
          version: latest
      -
        name: Available Platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Build
        uses: docker/build-push-action@v2.6.1
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          push: false
    env:
      PLATS: linux/386,linux/amd64,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm64
